### ISSUE TITLE
Could not find a declaration file for module 'vite-plugin-scope-tailwind'

### ISSUE THREAD

**Issue by Dorianslavov** [dolanmiu/vite-plugin-scope-tailwind#5]
After importing the module in `vite.config` I get this error in the terminal

```
Could not find a declaration file for module 'vite-plugin-scope-tailwind'. '/Users/dorianslavov/Desktop/efirma/node_modules/.pnpm/vite-plugin-scope-tailwind@1.1.10/node_modules/vite-plugin-scope-tailwind/dist/cjs/index.cjs' implicitly has an 'any' type.

Try `npm i --save-dev @types/vite-plugin-scope-tailwind` if it exists or add a new declaration (.d.ts) file containing `declare module 'vite-plugin-scope-tailwind';`
```

Shows in the package import as well
<img width="1043" alt="image" src="https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/25179716/1d91d70a-2c4c-4284-b35f-a953967a0f74">

Any ideas ?

**Comment by abeisleem** [comment]
experiencing the same issue. using with preact: 10.19.3 and typescript

**Comment by asanehisa** [comment]
Same. I suspect it is b/c I am using typescript.

**Comment by spa5k** [comment]
Just add `@ts-ignore` and ignore it, works without typescript.
